org: mozillaiamcis
service: hris-publisher
custom:
  hrisPublisherStage: ${opt:stage, self:provider.stage}
  hrisPublisherEnvironment:
    CIS_ENVIRONMENT:
      production: production
      development: development
      testing: testing
    DYNAMODB_TABLE:
      production: production-identity-vault
      development: development-identity-vault
      testing: testing-identity-vault
    IDENTIFIER:
      production: api.sso.mozilla.com
      development: api.dev.sso.allizom.org
      testing: api.test.sso.allizom.org
    CIS_PERSON_API_URL:
      production: person.api.sso.mozilla.com
      development: person.api.dev.sso.allizom.org
      testing: person.api.test.sso.allizom.org
    CIS_CHANGE_API_URL:
      production: change.api.sso.mozilla.com
      development: change.api.dev.sso.allizom.org
      testing: change.api.test.sso.allizom.org
    CIS_AUTHZERO_DOMAIN:
      production: auth.mozilla.auth0.com
      development: auth.mozilla.auth0.com
      testing: auth.mozilla.auth0.com
    CIS_SECRET_MANAGER_SSM_PATH:
      production: /iam/cis/production/hris_publisher
      development: /iam/cis/development/hris_publisher
      testing: /iam/cis/testing/hris_publisher
    CIS_DISCOVERY_URL:
      production: https://auth.mozilla.com/.well-known/mozilla-iam
      development: https://auth.allizom.org/.well-known/mozilla-iam
      testing: https://auth.allizom.org/.well-known/mozilla-iam
    BUCKET_ARN:
      production: arn:aws:s3:::cache.hris.sso.mozilla.com
      testing: arn:aws:s3:::cache.hris.test.sso.allizom.org
      development: arn:aws:s3:::cache.hris.dev.sso.allizom.org
    CIS_BUCKET_URL:
      production: cache.hris.sso.mozilla.com
      testing: cache.hris.test.sso.allizom.org
      development: cache.hris.dev.sso.allizom.org
    CIS_HRIS_CACHE_TIME_HOURS:
      production: 2
      testing: 2
      development: 2
provider:
  name: aws
  stage: ${opt:stage, 'development'}
  region: us-west-2
  runtime: python3.9
  architecture: x86_64
  tracing:
    lambda: true
  environment:
    CIS_ENVIRONMENT: ${self:custom.hrisPublisherEnvironment.CIS_ENVIRONMENT.${self:custom.hrisPublisherStage}}
    CIS_API_IDENTIFIER: ${self:custom.hrisPublisherEnvironment.IDENTIFIER.${self:custom.hrisPublisherStage}}
    CIS_PERSON_API_URL: ${self:custom.hrisPublisherEnvironment.CIS_PERSON_API_URL.${self:custom.hrisPublisherStage}}
    CIS_CHANGE_API_URL: ${self:custom.hrisPublisherEnvironment.CIS_CHANGE_API_URL.${self:custom.hrisPublisherStage}}
    CIS_AUTHZERO_TENANT: ${self:custom.hrisPublisherEnvironment.CIS_AUTHZERO_DOMAIN.${self:custom.hrisPublisherStage}}
    CIS_SECRET_MANAGER_SSM_PATH: ${self:custom.hrisPublisherEnvironment.CIS_SECRET_MANAGER_SSM_PATH.${self:custom.hrisPublisherStage}}
    CIS_DISCOVERY_URL: ${self:custom.hrisPublisherEnvironment.CIS_DISCOVERY_URL.${self:custom.hrisPublisherStage}}
    CIS_SIGNING_KEY_NAME: hris_signing_key
    CIS_REQUESTS_CACHE_BACKEND: memory
    CIS_WELL_KNOWN_MODE: https
    CIS_PUBLIC_KEY_NAME: publisher
    CIS_SECRET_MANAGER: aws-ssm
    CIS_BUCKET_URL: ${self:custom.hrisPublisherEnvironment.CIS_BUCKET_URL.${self:custom.hrisPublisherStage}}
    CIS_HRIS_CACHE_TIME_HOURS: ${self:custom.hrisPublisherEnvironment.CIS_HRIS_CACHE_TIME_HOURS.${self:custom.hrisPublisherStage}}
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - "lambda:InvokeFunction"
        - "lambda:InvokeAsync"
      Resource:
        - arn:aws:lambda:us-west-2:320464205386:function:hris-publisher-${self:custom.hrisPublisherStage}-handler
    - Effect: Allow
      Action:
        - "ssm:GetParameterHistory"
        - "ssm:GetParametersByPath"
        - "ssm:GetParameters"
        - "ssm:GetParameter"
      Resource:
        - arn:aws:ssm:*:*:parameter${self:custom.hrisPublisherEnvironment.CIS_SECRET_MANAGER_SSM_PATH.${self:custom.hrisPublisherStage}}/*
    - Effect: Allow
      Action:
        - "kms:Decrypt"
      Resource:
        - arn:aws:kms:us-west-2:320464205386:key/ef00015d-739b-456d-a92f-482712af4f32
    - Effect: Allow
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        - ${self:custom.hrisPublisherEnvironment.BUCKET_ARN.${self:custom.hrisPublisherStage}}
        - ${self:custom.hrisPublisherEnvironment.BUCKET_ARN.${self:custom.hrisPublisherStage}}/*
functions:
  handler:
    handler: handler.handle
    events:
      - schedule:
          rate: rate(6 hours)
          enabled: true
    description: hris-publisher for synchronizing HRIS to identity vault.
    memorySize: 3008 # This is HUGE because cpu allocation is tied to memorySize.
    timeout: 900
    layers:
      -  ${ssm:/iam/cis/${self:custom.hrisPublisherStage}/build/lambda_layer_arn}
