name: make-test

# TODO: on: [push, pull_request]
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          # GitHub.com > (this repo) > Settings > Secrets
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          # TODO: find a way to avoid this or make it compatible with on: [pull_request]
      - name: Run make test
        run: |
          make test
